# lab

How to watch dmesg live ?!

run this script: `sudo sh printk_live.sh`

### link:../main/container_of.c[container_of.c] module
Simple use of `container_of` macro.

###### link:../main/container_of_container_of.c[container_of_container_of.c] module
I tried to make things more complicated by accessing the `container_of` of the `container_of` struct. `insmod` it & `dmesg`.

### link:../main/list.c[list.c] module
Simple example of `<linux/list.h>`. `insmod` it & `dmesg`.

### link:../main/hashtable.c[hashtable.c] module
Simple example of `<linux/hashtable.h>`. `insmod` it & `dmesg`.

###### link:../main/phone_table.c[phone_table.c] module
Another example of `<linux/hashtable.h>`. `insmod` it & `dmesg`.

### link:../main/wait_queue.c[wait_queue.c] module
*please* read header comment in wait_queue.c to refresh your knowledge.

###### link:../main/wait_queue_proc.c[wait_queue_proc.c] module
First let me explain to you what should the module do:

After inserting the module, it will wait for you until you give it a specific action to complete the rest of its work.

This behavior is just like link:https://github.com/smalinux/lab/#static_completionc-and-dynamic_completionc-modules[a completion]. `a completion` built on top of `waitqueue`.

How to use: (watch dmesg live)
----
$ insmod wait_queue.ko &
$ echo "hi" > /proc/mydev &
$ echo "bla" > /proc/mydev &
$ rmmod wait_queue.ko
----

###### link:../main/waitqueue2.c[waitqueue2.c] module
Another example for *static* waitqueue

How to use: (watch dmesg live)
----
$ sudo insmod waitqueue2.ko
$ sudo cat /dev/etx_device
$ rmmod waitqueue2
----
link:../main/waitqueue3.c[here] is a *dynamic* version.

### link:../main/params.c[params.c] module
Passing Arguments to Device Driver. like: argc & argv

How to use:
----
$ insmod params.ko myshort=5 myint=100 mystring="Sohaib" myintArray=3,7
----

###### link:../main/cb_params.c[cb_params.c] module
Register the callback whenever the argument (parameter) got changed. 

insmod & enjoy watching dmesg live!
----
$ insmod cb_params.ko myint=50
$ echo 333 > /sys/module/cb_params/parameters/myint
----

### link:../main/cdev.c[cdev.c] module
Complete char device driver with user-level app for testing.

to test the driver: 
----
$ ./test_cdev
----

### link:../main/sys_fs.c[sys_fs.c] module
link:https://unix.stackexchange.com/q/4884/265591[What is the difference between procfs and sysfs?]

How to use:
----
$ insmod sys_fs.ko
$ ls /sys/kernel/sma_sysfs/
$ cat /sys/kernel/sma_sysfs/sma_value
$ echo 44 > /sys/kernel/sma_sysfs/sma_value
$ cat /sys/kernel/sma_sysfs/sma_value
$ rmmod sys_fs
----

Please read `Documentation/filesystems/sysfs.rst` and `Documentation/core-api/kobject.rst`

### link:../main/debugfs.c[debugfs.c] module
How to use:
----
$ insmod debugfs.ko
$ ls -l /sys/kernel/debug/sma_debugfs/
$ cat /sys/kernel/debug/sma_debugfs/sma_u8
$ echo 77 > /sys/kernel/debug/sma_debugfs/sma_u8
$ cat /sys/kernel/debug/sma_debugfs/sma_u8
$ rmmod debugfs
----


Please read `Documentation/filesystems/debugfs.rst` *(Done)*

### link:../main/ioctl.c[ioctl.c] module
How to use:
----
$ insmod ioctl.ko
$ ./test_ioctl
----

Nice example from other people:

* https://github.com/smalinux/km-session
* https://github.com/smalinux/linux-kernel-module-cheat/blob/master/kernel_modules/ioctl.c

please see 

* `Documentation/driver-api/ioctl.rst`
* ioctl man page
* https://stackoverflow.com/questions/15807846/ioctl-linux-device-driver
* Google: ioctl linux kernel

### link:../main/kthread.c[kthread.c] module
How to use: (watch dmesg live)
----
$ insmod kthread.ko
----

See your kernel thread:
----
$ ps -aux | grep "SMA Thread"
----

### link:../main/export_symbols.c[export_symbols.c] and link:../main/use_symbols.c[use_symbols.c] modules
*export_symbols.c* shares some dummy symbols (variables & functions).

*use_symbols.c* uses these dummy symbols.
How to use: (insert and remove use_symbols.ko many times and watch dmesg)
----
$ insmod export_symbols.ko
$ insmod use_symbols.ko
$ rmmod use_symbols
$ insmod use_symbols.ko
$ rmmod use_symbols
$ insmod use_symbols.ko
$ rmmod use_symbols
----

Check if your symbols really engaged to your kernel:
----
$ cat /proc/kallsyms | grep SOHAIB_
$ cat /proc/kallsyms | grep sohaib_
----
I made a very nice trick :D see `link:../main/trick_kallysms.c[trick_kallysms.c]` module.

After inserting `export_symbols.c` module I took the address of `SOHAIB_CONUT` symbol from `/proc/kallsyms` file, then I used it as a hard code in `trick_kallysms.c` :))

### link:../main/mutex.c[mutex.c] module
How to use it: `insmod mutex.ko` and enjoy watching dmesg live.

Prerequisites: Make should you understand link:https://github.com/smalinux/lab#kthreadc-module[Kthread].

This code snippet explains how to create two threads that access a global variable (etx_gloabl_variable). So before accessing the variable, it should lock the mutex. After that, it will release the mutex.

This way is *not* the most optimal way for locking, because whole the critical section is just singel int var, and you used *mutex* for locking, this adds moree overhead, the best way here is to use `link:https://github.com/smalinux/lab#atomicc-module[Atomic ops]`.

### link:../main/atomic.c[atomic.c] module
Trivial example touchs some `Atomic ops APIs`.

link:../main/atomic2.c[Another] nice example. `insmod` it and `dmesg` it live..

### link:../main/spinlock.c[spinlock.c] module
How to use it: `insmod spinlock.ko` and enjoy watching dmesg live.

Prerequisites: Make should you understand link:https://github.com/smalinux/lab#kthreadc-module[Kthread].

This code snippet explains how to create two threads that access a global variable (etx_gloabl_variable). So before accessing the variable, it should lock the spinlock. After that, it will release the spinlock.

Here is link:../main/rwlock.c[Read write spinlock] example. `insmod` it and `dmesg` it live..

Here is link:../main/seqlock.c[seqlock.c] example. `insmod` it and `dmesg` it live..

Reference:

* `Documentation/kernel-hacking/locking.rst`
* `Documentation/locking/spinlocks.rst`
* `Documentation/locking/locktypes.rst`

### ~~Workqueue~~
part 1: https://embetronicx.com/tutorials/linux/device-drivers/workqueue-in-linux-kernel/

part 2: https://embetronicx.com/tutorials/linux/device-drivers/workqueue-in-linux-dynamic-creation/

own workqueue: https://embetronicx.com/tutorials/linux/device-drivers/work-queue-in-linux-own-workqueue/

### ~~Tasklets~~
Two articles

tasklet.c  trivial example

tasklet2.c embetronicx example

### link:../main/timer.c[timer.c] module
Simple example of `<linux/timer.h>`. `insmod` it & enjoy watching `dmesg` live.

Read this again: https://embetronicx.com/tutorials/linux/device-drivers/using-kernel-timer-in-linux-device-driver/
https://embetronicx.com/tutorials/linux/device-drivers/using-high-resolution-timer-in-linux-device-driver/

### link:../main/misc_driver.c[misc_driver.c] module
What misc driver mean?! link:https://stackoverflow.com/a/18456796/5688267[What is the difference between misc drivers and char drivers?!]

How to use it:
----
$ insmod misc_driver.ko
$ ls -l /dev/simple_sma_misc
$ echo 1 > /dev/simple_sma_misc
$ cat /dev/simple_sma_misc
$ rmmod misc_driver
----

### link:../main/static_completion.c[static_completion.c] and link:../main/dynamic_completion.c[dynamic_completion.c] modules
Read `Documentation/scheduler/completion.rst`

First, Let me explain to you the concept of driver code.

In this source code, two places we are sending the complete call. One from the read function and another one from the driver exit function.

I’ve created one thread (`wait_function`) which has `while(1)`. That thread will always wait for the event to complete. It will be sleeping until it gets a complete call. When it gets the complete call, it will check the condition. If the condition is 1 then the complete came from the read function. It is 2, then the complete came from the exit function. If complete came from the read function, it will print the read count and it will again wait. If it is coming from the exit function, it will exit from the thread.

Here I’ve added two versions of code.

* Completion created by static method
* Completion created by dynamic method

But operation wise, both are the same.

How to use it - watch dmesg live: ( static version)
----
$ insmod static_completion.ko
$ sudo cat /dev/sma_device
$ rmmod static_completion
----

How to use it - watch dmesg live: ( dynamic version)
----
$ insmod dynamic_completion.ko
$ sudo cat /dev/sma_device
$ rmmod dynamic_completion
----

### mmap
subset of fops

https://stackoverflow.com/questions/10760479/how-to-mmap-a-linux-kernel-buffer-to-user-space/10770582#10770582

https://github.com/cirosantilli/linux-kernel-module-cheat/tree/59960b808cdf4d468112b8e116b5c2fa94627c92#mmap


### link:../main/vfs.c[vfs.c] module
My custom virtual file system

How to use it:
----
$ insmod sma_vfs.ko
$
$ rmmod sma_vfs
----

Further reading

* link:https://github.com/smalinux/linux-kernel-labs.github.io/blob/master/tmp/_sources/labs/filesystems_part1.rst.txt[File system drivers (Part 1)]
* link:https://github.com/smalinux/linux-kernel-labs.github.io/blob/master/tmp/_sources/labs/filesystems_part2.rst.txt[File system drivers (Part 2)]
* Documentation/filesystems/vfs.rst





 
